# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - aspenmesh/private-istio
  - aspenmesh/private-cni
  - aspenmesh/private-proxy
  - aspenmesh/istio-test-infra

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/cluster/jobs/aspenmesh/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - aspenmesh/istio-test-infra
    channels:
    - am-prow
    whitelist:
    - istio-testing

lgtm:
- repos:
  - aspenmesh/private-istio
  - aspenmesh/private-cni
  - aspenmesh/private-proxy
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"

plugins:
  aspenmesh/private-istio:
  - size
  - trigger
  - wip

  aspenmesh/private-cni:
  - size
  - trigger
  - wip 

  aspenmesh/private-proxy:
  - size
  - trigger
  - wip   

  aspenmesh/private-istio-releases:
  - size
  - trigger
  - wip

  aspenmesh/istio-test-infra:
  - size
  - assign
  - config-updater
  - golint
  - hold
  - lifecycle
  - skip
  - slackevents

external_plugins:
  aspenmesh/private-istio:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
      
  aspenmesh/private-cni:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request 

  aspenmesh/private-proxy:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request 